version: 2

models:
  - name: fct_orders
    description: |
      Orders Fact Table
      
      **Granularity**: 1 row per order per product.
      
      **Use**: Sales analysis, revenue, customer behavior.
    columns:
      - name: order_id
        description: "Unique identifier for the order"
      - name: order_tier
        description: |
          Classification of the order by value:
          - High Value: > $100
          - Medium Value: $50-$100
          - Low Value: < $50